import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import GoogleSignIn from "../components/auth/GoogleSignIn";
import { useAtomValue } from "jotai";
import UserAtom from "../components/auth/User";

const Home: NextPage = () => {
  const user = useAtomValue(UserAtom);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img
          src={"/logo.png"}
          alt="logo"
          style={{
            width: 300,
            height: 300,
          }}
        />


        <GoogleSignIn />
      </main>
    </div>
  );
};

export default Home;
